### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by RektPunk** [RektPunk/GEVBoost#2]
## TODO
- [ ] review NGBoost
  - [ ] check can I use it and how to use it
  - [ ] check another GBM to do this.
- [ ] review GEV distribution
  - [ ] check how to get gradient and hess 
  - [ ] Implement it to python code
- [ ] Make GEVBoost prototype
- [ ] Test it with generated toy example
- [ ] Test it with Real data
